# Generated by Django 4.2.5 on 2023-10-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_recipe', '0002_alter_recipe_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.FileField(upload_to='new_recipe'),
        ),
    ]
