# Generated by Django 4.2.5 on 2023-10-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_recipe', '0004_alter_recipe_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='desc',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='new_recipe/uploads'),
        ),
    ]
