# Generated by Django 4.2.5 on 2023-10-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_recipe', '0006_alter_recipe_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='vegModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isVeg', models.BooleanField(default=False)),
            ],
        ),
    ]
