# Generated by Django 4.2.5 on 2023-10-29 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_recipe', '0007_vegmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vegModel',
        ),
    ]
